#!/usr/bin/perl
use strict;
use warnings;
my $config = {
	REMOTE_SUFFIX => '',
	LOCAL_SUFFIX => '.',
	GM_SUFFIX => undef,
};

my $args = $#ARGV + 1;

die "Please supply the base URL\n" unless $args > 0;
die "Fewer arguments!\n" unless $args <= 2;

$ARGV[1] = '' unless defined $ARGV[1];

open (my $fh, '<', ".remotes") or exit 0;
while (<$fh>){
    chomp;

    s/#.*$//;              # Remove comments (can be suffix)
    next if /^\s*$/;       # Skip lines of pure whitespace
    next if /.*:.*:.*:.*/; # Skip 4-column lines (reserved)
    s/\s+$//;              # Remove trailing whitespace (can happen after stripping inline comments)

    my ($REMOTE_REL, $LOCAL_REL, $GM_REL) = split /:/;
    $REMOTE_REL = '' unless defined ($REMOTE_REL);
    $LOCAL_REL = '' unless defined ($LOCAL_REL);
    $GM_REL = '' unless defined ($GM_REL);

	if ($REMOTE_REL eq '') {
		$config->{$LOCAL_REL} = $GM_REL;
		next;
	}

    $LOCAL_REL = $REMOTE_REL unless ($LOCAL_REL ne '');

	my $remotePath = "$config->{REMOTE_SUFFIX}/$REMOTE_REL";
	my $localPath = "$config->{LOCAL_SUFFIX}/$LOCAL_REL";
	my $mediaPath = join('/', grep {$_} $config->{GM_SUFFIX}, $GM_REL);
	my $configCmd = $ARGV[1];

	system qq!git clone --no-checkout "$ARGV[0]/$remotePath" "$localPath"!;
	system qq!(cd "$localPath" && gmc "$ARGV[0]" "$ARGV[1]")!;
	system qq!(cd "$localPath" && $configCmd "$mediaPath")! if $configCmd;
	system qq!(cd "$localPath" && git reset --hard)!;
}
